lib/codesio_web/router.ex
defmodule CodesioWeb.Router do
  use CodesioWeb, :router
  use Coherence.Router
  alias Codesio.Accounts

  pipeline :always do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :put_user_score
  end

  pipeline :api do
    plug :accepts, ["json"]
  end
  pipeline :authorization do

  end
  pipeline :admin do
    plug CodesioHelpers.AuthorizationServices.Policies, :admin
  end

  pipeline :browser do
    plug Coherence.Authentication.Session
  end

  pipeline :protected do
    plug Coherence.Authentication.Session, protected: true
    plug :put_user_token
    plug :put_user_score
  end

  defp put_user_token(conn, _) do
    if current_user = conn.assigns[:current_user] do
      token = Phoenix.Token.sign(conn, "user socket", current_user.id)
      assign(conn, :user_token, token)
    else
      conn
    end
  end

  defp put_user_score(conn, _) do
    if current_user = conn.assigns[:current_user] do
      score = Accounts.get_user(conn.assigns[:current_user].id).score
      assign(conn, :user_score, score)
    else
      assign(conn, :user_score, 0)
    end
  end

  scope "/" do
    pipe_through :always
    pipe_through :browser
    coherence_routes()
  end

  scope "/" do
    pipe_through :always
    pipe_through :protected
    pipe_through :authorization
    coherence_routes :protected
  end

  scope "/", CodesioWeb do
    pipe_through :always
    pipe_through :protected
    pipe_through :authorization
    pipe_through :browser
    get "/users", UserController, :index
    get "/users/:username", UserController, :show
    resources "/snippets", SnippetController, except: [:index, :show]
  end

  scope "/", CodesioWeb do
    pipe_through :always
    pipe_through :browser # Use the default browser stack
    get "/", SnippetController, :index
    get "/snippets", SnippetController, :index
    get "/snippets/:id", SnippetController, :show
  end

  scope "/admin", CodesioWeb.Admin, as: :admin do
    pipe_through :always
    pipe_through :protected
    pipe_through :authorization
    pipe_through :admin
    resources "/snippets", SnippetController
    resources "/banned_ips", BannedIpController
  end

  # Other scopes may use custom stacks.
  # scope "/api", CodesioWeb do
  #   pipe_through :api
  # end
end

lib/codesio_web/views/coherence/layout_view.ex
defmodule CodesioWeb.Coherence.LayoutView do
  use CodesioWeb.Coherence, :view
end

lib/codesio_web/views/layout_view.ex
defmodule CodesioWeb.LayoutView do
  use CodesioWeb, :view
  def conditional_classes_for_body(conn, view_template) do
    case js_view_name(conn, view_template) do
      "SnippetNewView" -> "purple darken-2"
      "SnippetShowView" -> "purple darken-2"
      "SnippetEditView" -> "purple darken-2"
      _ -> ""
    end
  end
  def js_view_name(conn, view_template) do
    [view_name(conn), template_name(view_template)]
    |> Enum.reverse
    |> List.insert_at(0, "view")
    |> Enum.map(&String.capitalize/1)
    |> Enum.reverse
    |> Enum.join("")
  end
  defp view_name(conn) do
    conn
    |> view_module
    |> Phoenix.Naming.resource_name
    |> String.replace("_view", "")
  end
  defp template_name(template) when is_binary(template) do
    template
    |> String.split(".")
    |> Enum.at(0)
  end
end

lib/codesio_web/templates/layout/admin.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Codesio!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
            <li><a href="http://www.phoenixframework.org/docs">Get Started</a></li>
          </ul>
        </nav>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/codesio_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Think of Snippy as an instagram for code snippets. Submit snippets, vote on them and 
    find the snippets most useful for what you are working on.">
    <meta name="author" content="Ian T Butler">
    <meta name="user-token" content="<%= assigns[:user_token] %>">
    <title>It looks like you're trying to find some code.</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/js/materialize.min.js"></script>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body class="<%=conditional_classes_for_body(@conn, @view_template)%>" data-js-view-name="<%= js_view_name(@conn, @view_template) %>">
      <header class="header">
        <nav role="navigation">
          <div class="nav-wrapper">
            <ul id="nav-mobile" class="right high-on-med-and-down">
              <%= if Coherence.current_user_name(@conn) == nil do %>
                <li><a href="/sessions/new">Login</a></li>
              <% else %>
                <li>Job's Saved: <%= @user_score %></li>
                <li><%= link "Users", to: user_path(@conn, :index) %></li>
                <li><%= link "My Profile", to: user_path(@conn, :show, Coherence.current_user(@conn).username) %></li>
                <li><%= CodesioWeb.Coherence.ViewHelpers.signout_link(@conn) %></li>
              <% end %>
              <%# <li><a href="http://www.phoenixframework.org/docs">Donate</a></li> %>
            </ul>
          </div>
        </nav>
      </header>
      <div class="container" id="app-container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <div class='sub-container' >
        <main role="main">
          <%= render @view_module, @view_template, assigns %>
        </main>
      </div>
    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/codesio_web/templates/layout/torch.html.eex
<html>
  <head>
    <title>Admin</title>
    <!-- Uncomment to just use the bare bones torch styles rather than the theme -->
    <!--<link rel="stylesheet" href="<%= static_path(@conn, "/torch/base.css") %>">-->
    <link rel="stylesheet" href="<%= static_path(@conn, "/torch/theme.css") %>">
  </head>

  <body class="<%= Torch.PageView.body_classes(@conn) %>">
    <header>
      <section id="torch-account-info">
        <div class="torch-container">
          <a href="/">Home</a>
        </div>
      </section>

      <section id="torch-nav">
        <div class="torch-container">
          <div class="torch-logo">
            <a href="/">
              <h3>Torch: Snippy Admin Panel</h3>
            </a>
          </div>
          <nav class="torch-nav">
            <span><%= link "Snippets", to: admin_snippet_path(@conn, :index) %></span>
            <span><%= link "Banned Ips", to: admin_banned_ip_path(@conn, :index) %></span>
          </nav>
        </div>
      </section>
    </header>

    <%= Torch.FlashView.render("_flash_messages.html", assigns) %>
    <%= render @view_module, @view_template, assigns %>
    <script src="<%= static_path(@conn, "/torch/torch.js") %>"></script>
  </body>
</html>