lib/codesio_web/router.ex
defmodule CodesioWeb.Router do
  use CodesioWeb, :router
  use Coherence.Router
  alias Codesio.Accounts

  pipeline :always do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :put_user_score
  end

  pipeline :api do
    plug :accepts, ["json"]
  end
  pipeline :authorization do

  end
  pipeline :admin do
    plug CodesioHelpers.AuthorizationServices.Policies, :admin
  end

  pipeline :browser do
    plug Coherence.Authentication.Session
  end

  pipeline :protected do
    plug Coherence.Authentication.Session, protected: true
    plug :put_user_token
    plug :put_user_score
  end

  defp put_user_token(conn, _) do
    if current_user = conn.assigns[:current_user] do
      token = Phoenix.Token.sign(conn, "user socket", current_user.id)
      assign(conn, :user_token, token)
    else
      conn
    end
  end

  defp put_user_score(conn, _) do
    if current_user = conn.assigns[:current_user] do
      score = Accounts.get_user(conn.assigns[:current_user].id).score
      assign(conn, :user_score, score)
    else
      assign(conn, :user_score, 0)
    end
  end

  scope "/" do
    pipe_through :always
    pipe_through :browser
    coherence_routes()
  end

  scope "/" do
    pipe_through :always
    pipe_through :protected
    pipe_through :authorization
    coherence_routes :protected
  end

  scope "/", CodesioWeb do
    pipe_through :always
    pipe_through :protected
    pipe_through :authorization
    pipe_through :browser
    get "/users", UserController, :index
    get "/users/:username", UserController, :show
    resources "/snippets", SnippetController, except: [:index, :show]
  end

  scope "/", CodesioWeb do
    pipe_through :always
    pipe_through :browser # Use the default browser stack
    get "/", SnippetController, :index
    get "/snippets", SnippetController, :index
    get "/snippets/:id", SnippetController, :show
  end

  scope "/admin", CodesioWeb.Admin, as: :admin do
    pipe_through :always
    pipe_through :protected
    pipe_through :authorization
    pipe_through :admin
    resources "/snippets", SnippetController
    resources "/banned_ips", BannedIpController
  end

  # Other scopes may use custom stacks.
  # scope "/api", CodesioWeb do
  #   pipe_through :api
  # end
end

lib/codesio/accounts/user.ex
defmodule Codesio.Accounts.User do
  use Ecto.Schema
  import Ecto.Changeset
  use Coherence.Schema
  @derive {Phoenix.Param, key: :username}
  schema "users" do
    field :email, :string
    field :name, :string
    field :username, :string
    field :role, UserRoleEnum, default: :user
    field :score, :integer, default: 0
    has_many :votes, Codesio.Vote
    coherence_schema()
    timestamps()
  end

  @doc false
  def changeset(user, attrs) do
    user
    |> cast(attrs, [:name, :username, :email, :role, :score] ++ coherence_fields)
    |> validate_required([:name, :username, :email, :role, :score])
    |> unique_constraint(:username)
    |> unique_constraint(:email)
    |> validate_format(:email,~r/@/)
    |> validate_coherence(attrs)
  end

  def changeset(user, attrs, :password) do
    user
    |> cast(attrs, ~w(password, password_confirmation reset_password_token, reset_password_sent_at))
    |> validate_coherence_password_reset(attrs)
  end
end

lib/codesio_web/controllers/user_controller.ex
defmodule CodesioWeb.UserController do
  use CodesioWeb, :controller

  alias Codesio.Accounts
  alias Codesio.Accounts.User
  alias Codesio.SnippetsDisplay

  def index(conn, _params) do
    users = Accounts.list_users()
    render(conn, "index.html", users: users)
  end

  def show(conn, %{"username" => username}) do
    user = Accounts.get_user_by!(%{ username: username })
    user_snippets = SnippetsDisplay.snippets_for_user(user.id)
    render(conn, "show.html", user: user, user_snippets: user_snippets)
  end
end

lib/codesio_web/views/user_view.ex
defmodule CodesioWeb.UserView do
  use CodesioWeb, :view
  alias Codesio.Accounts.User
end

lib/codesio_web/templates/user/edit.html.eex
<h2>Edit User</h2>

<%= render "form.html", Map.put(assigns, :action, user_path(@conn, :update, @user)) %>

<span><%= link "Back", to: user_path(@conn, :index) %></span>

lib/codesio_web/templates/user/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :name, class: "control-label" %>
    <%= text_input f, :name, class: "form-control" %>
    <%= error_tag f, :name %>
  </div>

  <div class="form-group">
    <%= label f, :username, class: "control-label" %>
    <%= text_input f, :username, class: "form-control" %>
    <%= error_tag f, :username %>
  </div>

  <div class="form-group">
    <%= label f, :email, class: "control-label" %>
    <%= text_input f, :email, class: "form-control" %>
    <%= error_tag f, :email %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

lib/codesio_web/templates/user/index.html.eex
<div class= "user-page-index-container">
  <a class="btn btn-default btn-xs shades vibrant-indigo" href="javascript:history.back()">Go Back</a>
  <table class="table">
    <thead>
      <tr>
        <th>Username</th>
        <th>Email</th>
        <th>Job's Saved</th>
      </tr>
    </thead>
    <tbody>
      <%= for user <- @users do %>
        <tr class="user-page-table-row">
          <td><%= user.username %></td>
          <td><%= user.email %></td>
          <td><%= user.score %></td>
          <td class="text-right">
            <span><%= link "Show", to: user_path(@conn, :show, %User{username: user.username}), class: "btn btn-default btn-xs" %></span>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

lib/codesio_web/templates/user/new.html.eex
<h2>New User</h2>

<%= render "form.html", Map.put(assigns, :action, user_path(@conn, :create)) %>

<span><%= link "Back", to: user_path(@conn, :index) %></span>

lib/codesio_web/templates/user/show.html.eex
<div class="user-page-show-container">
  <a class="btn btn-default btn-xs" href="javascript:history.back()">Go Back</a>
  <div class="user-page-show-profile card small shades vibrant-indigo z-depth-2">
    <h2><%= @user.username %></h2>
    <li>
      <strong>Name:</strong>
      <%= @user.name %>
    </li>
    <li>
      <strong>Email:</strong>
      <%= @user.email %>
    </li>
    <li>
      <strong>Job's Saved:</strong>
      <%= @user.score %>
    </li>
  </div>
  <br />
  <h4 id="user-profile-snippet-title"><%= @user.username %>'s Snippets:</h4>
  <table class="table">
    <tbody>
      <%= for snippet <- @user_snippets do %>
        <tr class="user-page-table-row">
          <td>
            <label for="language">Language: </label>
            <span name="language"><%= snippet.language %></span>
          </td>
          <td>
            <label for="rating">Rating: </label>
            <span name="rating"><%= snippet.rating %></span>
          </td>
          <td>
            <%= link "Show", to: snippet_path(@conn, :show, snippet), class: "btn btn-default btn-xs" %>
          </td>
          <td class="tag-list shades midnight">
            <label for="rating">Tags: </label>
            <span name="rating"><%= Enum.join(String.split(snippet.tags, ","), ", ") %></span>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>